#!/usr/bin/env node

export const schema = {

  // ### GET /api/v1/channels/:ucid
  // *Schema*

  channels: {
    ucid: {
      author: String,
      authorId: String,
      authorUrl: String,
      authorBanners: [
        {
          url: String,
          width: Number,
          height: Number
        }
      ],
      authorThumbnails: [
        {
          url: String,
          width: Number,
          height: Number
        }
      ],

      subCount: Number,
      totalViews: Number,
      joined: Number,

      // paid: Boolean,
      autoGenerated: Boolean,
      // isFamilyFriendly: Boolean,
      description: String,
      // descriptionHtml: String,
      allowedRegions: Array(String),

      latestVideos: [
        {
          title: String,
          videoId: String,
          author: String,
          authorId: String,
          authorUrl: String,

          videoThumbnails: [
            {
              quality: String,
              url: String,
              width: Number,
              height: Number
            }
          ],
          description: String,
          // descriptionHtml: String,
          viewCount: Number,
          published: Number,
          publishedText: String,
          lengthSeconds: Number
          // paid: Boolean,
          // premium: Boolean
        }
      ],
      relatedChannels: [
        {
          author: String,
          authorId: String,
          authorUrl: String,
          authorThumbnails: [
            {
              url: String,
              width: Number,
              height: Number
            }
          ]
        }
      ]
    },

    // **Parameters**

    // | field   | value                                           |
    // |---------|-------------------------------------------------|
    // | sort_by | "newest", "oldest", "popular" (default: newest) |

    // Note that a channel's username (if it doesn't include spaces) is also valid in
    // place of ucid, e.g. /api/v1/channels/BlenderFoundation.

    // ### GET /api/v1/channels/:ucid/videos, /api/v1/channels/videos/:ucid

    // *Schema*

    videos: [
      {
        title: String,
        videoId: String,
        author: String,
        authorId: String,
        authorUrl: String,

        videoThumbnails: [
          {
            quality: String,
            url: String,
            width: Number,
            height: Number
          }
        ],
        description: String,
        // descriptionHtml: String,

        viewCount: Number,
        published: Number,
        publishedText: String,
        lengthSeconds: Number
        // paid: Boolean,
        // premium: Boolean
      }
    ]

    // **Parameters**

    // | field   | value                                           |
    // |---------|-------------------------------------------------|
    // | page    | Number                                           |
    // | sort_by | "newest", "oldest", "popular" (default: newest) |
  },

  // ### GET /api/v1/search

  // *Schema*

  search: [
    {
      // type: 'video',
      title: String,
      videoId: String,
      author: String,
      authorId: String,
      authorUrl: String,
      videoThumbnails: [
        {
          // quality: String,
          url: String
          // width: Number,
          // height: Number
        }
      ],
      description: String,
      // descriptionHtml: String,
      viewCount: Number,
      published: Number,
      publishedText: String,
      lengthSeconds: Number
      // liveNow: Boolean,
      // paid: Boolean,
      // premium: Boolean
    },
    {
      type: 'playlist',
      title: String,
      playlistId: String,
      author: String,
      authorId: String,
      authorUrl: String,
      videoCount: Number,
      videos: [
        {
          title: String,
          videoId: String,
          lengthSeconds: Number,
          videoThumbnails: [
            {
              // quality: String,
              url: String
              // width: Number,
              // height: Number
            }
          ]
        }
      ]
    },
    {
      type: 'channel',
      author: String,
      authorId: String,
      authorUrl: String,
      authorThumbnails: [
        {
          url: String
          // width: Number,
          // height: Number
        }
      ],
      subCount: Number,
      videoCount: Number,
      description: String
      // descriptionHtml: String
    }

    // **Parameters**

    // | field    | value                                                    |
    // |----------|----------------------------------------------------------|
    // | q        | String                                                   |
    // | page     | Number                                                   |
    // | sort_by  | "relevance", "rating", "upload_date", "view_count"       |
    // | date     | "hour", "today", "week", "month", "year"                 |
    // | duration | "short", "long"                                          |
    // | type     | "video", "playlist", "channel", "all", (default: video)  |
    // | features | "hd", "subtitles", "creative_commons", "3d", "live",     |
    // |          | "purchased", "4k", "360", "location", "hdr"              |
    // |          | (comma separated: e.g. "&features=hd,subtitles,3d,live") |
    // | region   | ISO 3166 country code (default: "US")                    |
  ]
}
